name: Get Citation Data

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          cd ./google_scholar_crawler
          pip install -r requirements.txt

      - name: Fetch Google Scholar data
        env:
          GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        run: |
          cd ./google_scholar_crawler
          python main.py

      - name: Publish citation data
        run: |
          cd ./google_scholar_crawler/results

          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          export remote_repo="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"

          git add *.json
          git commit -m "Updated Citation Data" || echo "No changes to commit"

          git branch -M google-scholar-stats
          git push "${remote_repo}" HEAD:google-scholar-stats --force