name: Get Citation Data

on:
  page_build:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          cd ./google_scholar_crawler
          pip install -r requirements.txt
          pip install "bibtexparser==1.4.3"

      - name: Get citation data
        env:
  GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
  SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: |
          cd ./google_scholar_crawler
          python main.py

          cd ./results

          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          export remote_repo="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"

          git add *.json
          git commit -m "Updated Citation Data" || echo "No changes to commit"

          git branch -M google-scholar-stats
          git push "${remote_repo}" HEAD:google-scholar-stats --force